---
title: "LatNet analysis"
output: html_notebook
---

# load test data from the CoRegNet package
```{r}
library(CoRegNet)
data("CIT_BLCA_EXP")
normal_samples <- which(grepl('^CITN', colnames(CIT_BLCA_EXP)))
cancerExp <- CIT_BLCA_EXP[,-normal_samples]
dim(cancerExp)
```

# load LatNet functions (YOU SHOULD SET YOUR OWN PATH)
```{r}
LatNet_Path <- '~/Documents/GitHub/LatNet/LatNet.R'
source(LatNet_Path)
```

# Infer regulatory network for the genes. You can load your network structure directly if it has been obtained with different means 
```{r}
# perform the inference as discribed in the coregnet package
# Load list of Human transcription factors
data(HumanTF)
 
# you can set the option parallel="multicore" to accelerate the inference in case you have a multicore computing infrastructure
# Generate the network 
GRN <- hLICORN(numericalExpression=cancerExp,
               TFlist = HumanTF,
               minGeneSupport = 0.2,
               minCoregSupport=0.2,
               maxCoreg = 3,
               verbose = TRUE,
               parallel = "no")
```

# generating regulator activity signals
```{r}
activity <- .regulatorActivity(GRN, cancerExp)
```

<!-- heatmap with influences -->
<!-- ```{r} -->
<!-- heatplot(influences[,names(CIT_BLCA_Subgroup)], groups = CIT_BLCA_Subgroup) -->
<!-- heatplot(inf[,names(CIT_BLCA_Subgroup)], groups = CIT_BLCA_Subgroup) -->
<!-- ``` -->

generating perturbations
```{r}
refData <- cancerExp
targetData <- cancerExp
ptm <- proc.time()
allperturbations.raw <- t(simplify2array(mclapply(targets(GRN), .oneGenePerturbations, GRN, t(refData), t(targetData), 0)))#, mc.cores = 3
rownames(allperturbations.raw) <- targets(GRN)
nrow(allperturbations.raw)
#remove the one having 0 everywhere
allperturbations <- allperturbations.raw[-which(rowSums(allperturbations.raw)==0),]
runtime <- proc.time() - ptm
print(runtime)
nrow(allperturbations)
```

Export all data if necessary
```{r}

ds1 <- t(cancerExp[c(targets(GRN), names(regulators(GRN))),names(CIT_BLCA_Subgroup)])
ds1 <- data.frame("subtype"=CIT_BLCA_Subgroup, ds1)

ds2 <- t(influences[,names(CIT_BLCA_Subgroup)])
ds2 <- data.frame("subtype"=CIT_BLCA_Subgroup, ds2)

ds3 <- t(allperturbations[,names(CIT_BLCA_Subgroup)])
ds3 <- data.frame("subtype"=CIT_BLCA_Subgroup, ds3)

write.csv(ds1, file = "/Users/dhifli/UsexpressionsAllCIT.csv")
write.csv(ds2, file = "/Users/dhifli/influencesAllCIT.csv")
write.csv(ds3, file = "/Users/dhifli/perturbationsAllCIT.csv")
```

